// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlbm9gX9vcANLE3wsD4AgTEcoZs7FXXaI',
    appId: '1:726899915896:web:e3ccf3a8bb50832ff6c18d',
    messagingSenderId: '726899915896',
    projectId: 'e-commerce-e3b5c',
    authDomain: 'e-commerce-e3b5c.firebaseapp.com',
    databaseURL: 'https://e-commerce-e3b5c-default-rtdb.firebaseio.com',
    storageBucket: 'e-commerce-e3b5c.appspot.com',
    measurementId: 'G-XPLPWSG6LK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1nvlA9jC7knu51G0zrmXmp58M4mlwJUE',
    appId: '1:726899915896:android:0eba5b7773f34a5bf6c18d',
    messagingSenderId: '726899915896',
    projectId: 'e-commerce-e3b5c',
    databaseURL: 'https://e-commerce-e3b5c-default-rtdb.firebaseio.com',
    storageBucket: 'e-commerce-e3b5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa6AT8FuiJmNutfQfZRyFZ2LvQy3PrKEc',
    appId: '1:726899915896:ios:205a69ca1c67e836f6c18d',
    messagingSenderId: '726899915896',
    projectId: 'e-commerce-e3b5c',
    databaseURL: 'https://e-commerce-e3b5c-default-rtdb.firebaseio.com',
    storageBucket: 'e-commerce-e3b5c.appspot.com',
    iosClientId: '726899915896-o5oe1askq22gepkii62do3avoh5160q8.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa6AT8FuiJmNutfQfZRyFZ2LvQy3PrKEc',
    appId: '1:726899915896:ios:0c726d4ad58c380cf6c18d',
    messagingSenderId: '726899915896',
    projectId: 'e-commerce-e3b5c',
    databaseURL: 'https://e-commerce-e3b5c-default-rtdb.firebaseio.com',
    storageBucket: 'e-commerce-e3b5c.appspot.com',
    iosClientId: '726899915896-td582jvsvskgicvf9ql3vhe09q26kh3e.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
